### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by Murthy10** [postgrespro/aqo#14]
I'm running into compilation issues during testing AQO.

Can you propose a release / tag of PostgreSQL and AQO which works together?

For example:
- PostgreSQL release REL9_6_14 (https://github.com/postgres/postgres/releases)
- AQO stable tag

**Comment by danolivo** [comment]
Ok. I will do it. I want to bring your attention that branch 'master' corresponds to current master of vanilla PostgreSQL. You used branch 'stable9_6'?
New versions of AQO contains functions that can't be developed in PostgreSQL v.9.6.
I recommend to use PostgreSQL v.11 or v.12 for more effectiveness and stability of results.

**Comment by danolivo** [comment]
I studied your issue.
Branches for previous PostgreSQL releases: stable9_6 and stable11 were tested and tagged by corresponding postgres versions.
I checked compilation issues and set tag 12beta3 to the corresponding commit of master branch.
Thanks for your interest.

**Comment by Murthy10** [comment]
Thank you for your fast answer and your additional effort.

So I tried it with:
- PostgreSQL 11 (REL_11_4)
- AQO stable11

Resulting in an error at the compilation of AQO:
```
cardinality_estimation.c:2:10: fatal error: optimizer/optimizer.h: No such file or directory
 #include "optimizer/optimizer.h"
```

**Comment by danolivo** [comment]
This line was introduced in commit 339f2ad for PostgreSQL 12beta3 version. In the stable11 I could not see this code. Check your AQO and PostgreSQL code branches.

**Comment by Murthy10** [comment]
You are right my fault. 
It compiled after:  `git checkout stable11`
